name: CI Pipeline

on:
  push:
    branches-ignore:
      - main
    # Runs when any branch except the main branch receives a push.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up language environment (Node.js, Python, etc.). Example for Node.js:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies (for Node.js)
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test

    # Build the project (modify as needed for your build process)
    - name: Build project
      run: npm run build

  merge:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge branch into main
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git checkout main
        git merge --no-ff ${{ github.ref }} -m "Merging ${GITHUB_REF} into main"
        git push origin main
