name: CI Pipeline

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Add your test and build steps here
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  merge:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set branch name variable
        id: vars
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Merge branch into main or master
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Checkout main or master
          if git show-ref --quiet refs/heads/main; then
            git checkout main
          else
            git checkout master
          fi
          
          # Merge the current branch into the main/master branch
          git merge --no-ff ${{ env.branch_name }} -m "Merging ${{ env.branch_name }} into main/master"
          
          # Push the changes using GitHub's built-in token
          git push origin HEAD

      - name: Delete source branch
        run: |
          if [ "${{ env.branch_name }}" != "main" ] && [ "${{ env.branch_name }}" != "master" ]; then
            git push origin --delete ${{ env.branch_name }}
          fi
